#!/bin/bash
# =============================================================================
# runc-grit: Wrapper around runc that adds CRIU --action-script for GPU restore
# =============================================================================
#
# This wrapper intercepts runc restore commands and injects CRIU's --action-script
# option to run cuda-checkpoint during the post-restore phase (before process wakes).
#
# Install:
#   sudo cp runc-grit-wrapper.sh /usr/local/bin/runc-grit
#   sudo chmod +x /usr/local/bin/runc-grit
#
# Configure containerd to use it by setting BinaryName = "runc-grit" in config.toml
#
# =============================================================================

REAL_RUNC="/usr/bin/runc"
LOG_FILE="/var/log/runc-grit.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

# Check if real runc exists
if [ ! -x "$REAL_RUNC" ]; then
    # Try to find runc
    for path in /usr/local/bin/runc /usr/sbin/runc; do
        if [ -x "$path" ]; then
            REAL_RUNC="$path"
            break
        fi
    done
fi

log "runc-grit called with: $*"

# Check if this is a restore command
IS_RESTORE=false
for arg in "$@"; do
    if [ "$arg" = "restore" ]; then
        IS_RESTORE=true
        break
    fi
done

if [ "$IS_RESTORE" = "true" ]; then
    log "Detected restore command, checking for GPU metadata..."
    
    # Parse arguments to find checkpoint image path
    IMAGE_PATH=""
    CONTAINER_ID=""
    BUNDLE_PATH=""
    
    PREV_ARG=""
    for arg in "$@"; do
        case "$PREV_ARG" in
            "--image-path") IMAGE_PATH="$arg" ;;
            "--bundle"|"-b") BUNDLE_PATH="$arg" ;;
        esac
        PREV_ARG="$arg"
        
        # Last non-option argument is usually the container ID
        if [[ ! "$arg" =~ ^- ]]; then
            CONTAINER_ID="$arg"
        fi
    done
    
    log "IMAGE_PATH=$IMAGE_PATH BUNDLE_PATH=$BUNDLE_PATH CONTAINER_ID=$CONTAINER_ID"
    
    # Look for GPU metadata in checkpoint directory
    GPU_METADATA=""
    if [ -n "$IMAGE_PATH" ]; then
        # Check parent directory for gpu-metadata.json
        PARENT_DIR=$(dirname "$IMAGE_PATH")
        if [ -f "$PARENT_DIR/gpu-metadata.json" ]; then
            GPU_METADATA="$PARENT_DIR/gpu-metadata.json"
        elif [ -f "$IMAGE_PATH/../gpu-metadata.json" ]; then
            GPU_METADATA="$IMAGE_PATH/../gpu-metadata.json"
        fi
    fi
    
    if [ -n "$GPU_METADATA" ] && [ -f "$GPU_METADATA" ]; then
        log "Found GPU metadata: $GPU_METADATA"
        
        # Read source GPU UUID from metadata
        SOURCE_GPU=$(cat "$GPU_METADATA" | grep -o '"sourceGPUUUIDs":\s*\["[^"]*"' | grep -o 'GPU-[^"]*')
        
        if [ -n "$SOURCE_GPU" ]; then
            log "Source GPU: $SOURCE_GPU"
            
            # Get destination GPU UUID
            DEST_GPU=$(nvidia-smi -L 2>/dev/null | grep -oP 'UUID: \K[^\)]+' | head -1)
            
            if [ -n "$DEST_GPU" ]; then
                log "Dest GPU: $DEST_GPU"
                DEVICE_MAP="${SOURCE_GPU}=${DEST_GPU}"
                log "Device map: $DEVICE_MAP"
                
                # Create action script for CRIU
                ACTION_SCRIPT=$(mktemp /tmp/grit-gpu-action-XXXXXX.sh)
                cat > "$ACTION_SCRIPT" << SCRIPT_EOF
#!/bin/bash
# GRIT GPU Restore Action Script - Generated by runc-grit
ACTION="\$1"
PID="\$CRTOOLS_INIT_PID"

LOG="/var/log/grit-gpu-restore-\$PID.log"

echo "[\$(date)] CRIU action: \$ACTION PID=\$PID" >> "\$LOG"

if [ "\$ACTION" != "post-restore" ]; then
    exit 0
fi

if [ -z "\$PID" ]; then
    echo "[\$(date)] ERROR: No PID from CRTOOLS_INIT_PID" >> "\$LOG"
    exit 0
fi

# Find cuda-checkpoint
CUDA_CKPT=""
for p in /usr/local/bin/cuda-checkpoint /usr/bin/cuda-checkpoint; do
    [ -x "\$p" ] && CUDA_CKPT="\$p" && break
done

if [ -z "\$CUDA_CKPT" ]; then
    echo "[\$(date)] ERROR: cuda-checkpoint not found" >> "\$LOG"
    exit 0
fi

echo "[\$(date)] Running GPU restore with device-map: $DEVICE_MAP" >> "\$LOG"

\$CUDA_CKPT --action restore --pid "\$PID" --device-map "$DEVICE_MAP" >> "\$LOG" 2>&1 || echo "[\$(date)] GPU restore error" >> "\$LOG"
\$CUDA_CKPT --toggle --pid "\$PID" >> "\$LOG" 2>&1 || echo "[\$(date)] GPU toggle error" >> "\$LOG"

echo "[\$(date)] GPU restore completed" >> "\$LOG"
exit 0
SCRIPT_EOF
                chmod +x "$ACTION_SCRIPT"
                log "Created action script: $ACTION_SCRIPT"
                
                # Call real runc with --action-script
                log "Calling: $REAL_RUNC $* --action-script $ACTION_SCRIPT"
                exec "$REAL_RUNC" "$@" --action-script "$ACTION_SCRIPT"
            else
                log "No destination GPU found, proceeding without GPU restore"
            fi
        else
            log "No source GPU UUID in metadata"
        fi
    else
        log "No GPU metadata found, proceeding with normal restore"
    fi
fi

# Default: pass through to real runc
log "Passing through to real runc: $REAL_RUNC $*"
exec "$REAL_RUNC" "$@"
